### ISSUE TITLE
More precise timeline for release

### ISSUE THREAD

**Issue by JBKnights** [PRBonn/kppr#1]
Hi!  I really enjoyed your paper, and in particular would really like to play around with your implementation of the contrastive loss for place recognition; would you be able to give any more information on the release schedule for your code than beginning of 2023?

Thanks,
Josh

**Comment by louis-wiesmann** [comment]
Hey Josh,
thanks for you interest, most likely soon after the ICRA deadline, so first week of march.

**Comment by YYYY1213800** [comment]
Hi ! I am also interested in this paper. Will it be open source recently in march?
thanks a lot

**Comment by louis-wiesmann** [comment]
I've uploaded the code and the model. Please let me know if you encounter any problems!
